/*
 * libmsr: A library to interact with MSRxxx magnetic card readers/writers
 */

#ifndef LIBMSR_H
#define LIBMSR_H

#include <Windows.h>

#define LIBMSRDECL __stdcall

#ifdef _DLL
#define LIBMSRAPI __declspec(dllexport) LIBMSRDECL
#else 
#define LIBMSRAPI __declspec(dllimport) LIBMSRDECL
#endif

typedef long LIBMSRSTATUS;
typedef void* LIBMSRHANDLE;

#define LIBMSR_OK 0L
#define LIBMSR_ERROR 0xC0000000L
#define LIBMSR_MEM_ALLOC_FAILED (LIBMSR_ERROR | 0x00000001)
#define LIBMSR_PORT_OPEN_FAILED (LIBMSR_ERROR | 0x00000002)
#define LIBMSR_PORT_SETUP_FAILED (LIBMSR_ERROR | 0x00000003)
#define LIBMSR_PORT_WRITE_FAILED (LIBMSR_ERROR | 0x00000004)
#define LIBMSR_PORT_READ_FAILED (LIBMSR_ERROR | 0x00000005)
#define LIBMSR_DEVICE_ERROR (LIBMSR_ERROR | 0x00010000L)
#define LIBMSR_DEVICE_SYNC_LOST (LIBMSR_DEVICE_ERROR | 0x00000001)
#define LIBMSR_DEVICE_COMMAND_FAILED (LIBMSR_DEVICE_ERROR | 0x00000002)

LIBMSRSTATUS LIBMSRAPI MSROpen(LPTSTR PortName, LIBMSRHANDLE *pHandle);

LIBMSRSTATUS LIBMSRAPI MSRReset(LIBMSRHANDLE Handle);

LIBMSRSTATUS LIBMSRAPI MSRLedAllOff(LIBMSRHANDLE Handle);
LIBMSRSTATUS LIBMSRAPI MSRLedAllOn(LIBMSRHANDLE Handle);
LIBMSRSTATUS LIBMSRAPI MSRLedGreenOn(LIBMSRHANDLE Handle);
LIBMSRSTATUS LIBMSRAPI MSRLedYellowOn(LIBMSRHANDLE Handle);
LIBMSRSTATUS LIBMSRAPI MSRLedRedOn(LIBMSRHANDLE Handle);

void LIBMSRAPI MSRClose(LIBMSRHANDLE Handle);

#endif /* LIBMSR_H */
